<?php
// program TestMain (generated by Structorizer 3.32-32) 

// Copyright (C) 2020-04-13 Kay Gürtzig 
// License: GPLv3-link 
// GNU General Public License (V 3) 
// https://www.gnu.org/licenses/gpl.html 
// http://www.gnu.de/documents/gpl.de.html 

// BEGIN initialization for "IncludeA" 
var a1: int;
a2 <- "doof";
// END initialization for "IncludeA" 
// BEGIN initialization for "IncludeB" 
var b1: string;
b2 <- 3.9;
// END initialization for "IncludeB" 

// function testSub 
function testSub(c1, param2: real; b1: string): int()
{
	global $a2, $a1;

	// TODO Establish sensible web formulars to get the $_GET input working. 

	d1 <- a1;
	d2 <- a2;
	a1 <- 15;
	return length(a2 + b1) + floor(c1) * ceil(param2);
}
// = = = = 8< = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

// program TestMain 
// Test for indirect and concurrent includes 

a1 <- 7;
b1 <- a2 + " oder blöd";
c1 <- a1 * b2;
c2 <- testSub(c1, a1 + b2, b1);
echo a1, " ", a2, " ", b1, " ", b2;

?>
