#!/bin/sh
set -e
################################################################################
#
#      Author:        Bob Fisch
#
#      Description:   create all-in-one jar file with all external jars included
#
################################################################################
#
#      Revision List
#
#      Author                        Date          Description
#      ------                        ----          -----------
#      Bob Fisch                     2008.10.15    First Issue
#      Bob Fisch & Philipp Hübner    2009.07.08    Scripting ameliorations
#      Bob Fisch                     2010.01.25    Update for new libraries and signature removing
#      Simon Sobisch                 2017.03.06    Check for jar, use comments instead of `echo`,
#                                                  using recursive cp for libs
#
################################################################################

# check for jar in PATH
jar 2>/dev/null 1>&2 || (rc=$? && if test $rc -gt 1; then (echo 'jar not found in $PATH' && exit $rc); fi)

# delete the old archive (if present)
[ -f structorizer.jar ] && rm structorizer.jar

# make directory
[ -d jar ] && rm -R jar
mkdir jar

# copy libs
cp -R lib/* jar

# change into jar directory
pushd jar

# decompress jars
echo "Decompressing jars ..."
jar xf bsh-2.0b4.jar
jar xf swing-layout-1.0.3.jar
jar xf freehep-graphics2d-2.1.1.jar
jar xf freehep-graphicsio-2.1.1.jar
jar xf freehep-io-2.0.2.jar
jar xf freehep-swing-2.0.3.jar
jar xf freehep-util-2.0.2.jar
jar xf freehep-xml-2.1.1.jar
jar xf freehep-graphicsio-svg-2.1.1.jar
jar xf freehep.jar

# deleting signatures
rm -f META-INF/*.SF
rm -f META-INF/*.DSA

# remove jar files
rm *.jar

# go back
popd

# copy other files
echo "Copying resources"
cp -R bin/* jar/

# create a new archive
echo "Create a new archive"
jar cmf structorizer.big.manifest structorizer.jar -C jar/ .

# remove the jar-directory
rm -R jar/

# execute the archive
echo "Running Structorizer from all-in-one jar"
java -jar structorizer.jar
