#!/bin/sh
set -e
################################################################################
#
#      Author:		Bob Fisch
#
#      Description:	
#
################################################################################
#
#      Revision List
#
#      Author						Date		Description
#      ------						----		-----------
#      Bob Fisch					2008.10.04  First Issue
#	   Bob Fisch & Philipp Hübner	2009.07.08  Scripting ameliorations
#
################################################################################

# delete the old archive (if present)
[ -f structorizer.jar ] && rm structorizer.jar

# create an new archive
jar cmf structorizer.manifest structorizer.jar -C bin/ .

# execute the archive
java -jar structorizer.jar