10 REM Tries to read as many integer values as possible upto maxNumbers 
20 REM from file fileName into the given array numbers. 
30 REM Returns the number of the actually read numbers. May cause an exception. 
40 REM Generated by Structorizer 3.32-36 
50 
60 REM Copyright (C) 2020-03-21 Kay Gürtzig 
70 REM License: GPLv3-link 
80 REM GNU General Public License (V 3) 
90 REM https://www.gnu.org/licenses/gpl.html 
100 REM https://www.gnu.de/documents/gpl-3.0.de.html 
110 
120 REM  
130 REM TODO: Add type-specific suffixes where necessary! 
140 FUNCTION readNumbers(fileName AS String, numbers AS integer(50), maxNumbers AS integer) AS integer
150   REM TODO: add the respective type suffixes to your variable names if required 
160   REM  
170   LET nNumbers = 0
180   LET fileNo = fileOpen(fileName)
190   IF fileNo <= 0 THEN
200     REM FIXME: Only a number is allowed as parameter: 
210     ERROR "File could not be opened!"
220   END IF
230   ON ERROR GOTO 310
240   DO WHILE NOT fileEOF(fileNo) AND nNumbers < maxNumbers
250     LET number = fileReadInt(fileNo)
260     LET numbers(nNumbers) = number
270     LET nNumbers = nNumbers + 1
280   LOOP
290   GOTO 340
300   REM Start of error handler, FIXME: variable 'error' should conatain error info ... 
310     REM FIXME: Only a number is allowed as parameter: 
320     ERROR 
330   REM End of error handler, resume here ... 
340   ON ERROR GOTO 0
350   fileClose(fileNo)
360   RETURN nNumbers
370 END FUNCTION
380 
390 REM ======= 8< =========================================================== 
400 
410 REM Computes the sum and average of the numbers read from a user-specified 
420 REM text file (which might have been created via generateRandomNumberFile(4)). 
430 REM  
440 REM This program is part of an arrangement used to test group code export (issue 
450 REM #828) with FileAPI dependency. 
460 REM The input check loop has been disabled (replaced by a simple unchecked input 
470 REM instruction) in order to test the effect of indirect FileAPI dependency (only the 
480 REM called subroutine directly requires FileAPI now). 
490 REM Generated by Structorizer 3.32-36 
500 
510 REM Copyright (C) 2020-03-21 Kay Gürtzig 
520 REM License: GPLv3-link 
530 REM GNU General Public License (V 3) 
540 REM https://www.gnu.org/licenses/gpl.html 
550 REM https://www.gnu.de/documents/gpl-3.0.de.html 
560 
570 REM  
580 REM program ComputeSum
590 REM TODO: add the respective type suffixes to your variable names if required 
600 DIM values() AS ???
610 REM  
620 LET fileNo = 1000
630 REM Disable this if you enable the loop below! 
640 PRINT "Name/path of the number file"; : INPUT file_name
650 REM If you enable this loop, then the preceding input instruction is to be disabled 
660 REM and the fileClose instruction in the alternative below is to be enabled. 
670 REM DO 
680 REM   PRINT "Name/path of the number file"; : INPUT file_name 
690 REM   LET fileNo = fileOpen(file_name) 
700 REM LOOP UNTIL fileNo > 0 OR file_name = "" 
710 IF fileNo > 0 THEN
720   REM This should be enabled if the input check loop above gets enabled. 
730 REM   fileClose(fileNo) 
740   LET nValues = 0
750   ON ERROR GOTO 790
760   LET nValues = readNumbers(file_name, values, 1000)
770   GOTO 830
780   REM Start of error handler, FIXME: variable 'failure' should conatain error info ... 
790     PRINT failure
800     REM FIXME: The following exit code was intended to pass: -7 
810     STOP
820   REM End of error handler, resume here ... 
830   ON ERROR GOTO 0
840   LET sum = 0.0
850   FOR k = 0 TO nValues-1
860     LET sum = sum + values(k)
870   NEXT k
880   PRINT "sum = "; sum
890   PRINT "average = "; sum / nValues
900 END IF
910 END

REM = = = = 8< = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

920 REM ======= 8< =========================================================== 
930 
940 REM Reads a random number file and draws a histogram accotrding to the 
950 REM user specifications 
960 REM Generated by Structorizer 3.32-36 
970 
980 REM Copyright (C) 2020-03-21 Kay Gürtzig 
990 REM License: GPLv3-link 
1000 REM GNU General Public License (V 3) 
1010 REM https://www.gnu.org/licenses/gpl.html 
1020 REM https://www.gnu.de/documents/gpl-3.0.de.html 
1030 
1040 REM  
1050 REM program DrawRandomHistogram
1060 REM TODO: add the respective type suffixes to your variable names if required 
1070 DIM numberArray() AS ???
1080 DIM count() AS Integer
1090 REM  
1100 LET fileNo = -10
1110 DO
1120   PRINT "Name/path of the number file"; : INPUT file_name
1130   LET fileNo = fileOpen(file_name)
1140 LOOP UNTIL fileNo > 0 OR file_name = ""
1150 IF fileNo > 0 THEN
1160   fileClose(fileNo)
1170   PRINT "number of intervals"; : INPUT nIntervals
1180   REM Initialize the interval counters 
1190   FOR k = 0 TO nIntervals-1
1200     LET count(k) = 0
1210   NEXT k
1220   REM Index of the most populated interval 
1230   LET kMaxCount = 0
1240   LET nObtained = 0
1250   ON ERROR GOTO 1290
1260   LET nObtained = readNumbers(file_name, numberArray, 10000)
1270   GOTO 1310
1280   REM Start of error handler, FIXME: variable 'failure' should conatain error info ... 
1290     PRINT failure
1300   REM End of error handler, resume here ... 
1310   ON ERROR GOTO 0
1320   IF nObtained > 0 THEN
1330     LET min = numberArray(0)
1340     LET max = numberArray(0)
1350     FOR i = 1 TO nObtained-1
1360       IF numberArray(i) < min THEN
1370         LET min = numberArray(i)
1380       ELSE
1390         IF numberArray(i) > max THEN
1400           LET max = numberArray(i)
1410         END IF
1420       END IF
1430     NEXT i
1440     REM Interval width 
1450     LET width = (max - min) * 1.0 / nIntervals
1460     FOR i = 0 TO nObtained - 1
1470       LET value = numberArray(i)
1480       LET k = 1
1490       DO WHILE k < nIntervals AND value > min + k * width
1500         LET k = k + 1
1510       LOOP
1520       LET count(k-1) = count(k-1) + 1
1530       IF count(k-1) > count(kMaxCount) THEN
1540         LET kMaxCount = k-1
1550       END IF
1560     NEXT i
1570     CALL drawBarChart(count, nIntervals)
1580     PRINT "Interval with max count: "; kMaxCount; " ("; count(kMaxCount); ")"
1590     FOR k = 0 TO nIntervals-1
1600       PRINT count(k); " numbers in interval "; k; " ("; min + k * width; " ... "; min + (k+1) * width; ")"
1610     NEXT k
1620   ELSE
1630     PRINT "No numbers read."
1640   END IF
1650 END IF
1660 END
1670 REM  
1680 REM Draws a bar chart from the array "values" of size nValues. 
1690 REM Turtleizer must be activated and will scale the chart into a square of 
1700 REM 500 x 500 pixels 
1710 REM Note: The function is not robust against empty array or totally equal values. 
1720 REM TODO: Add type-specific suffixes where necessary! 
1730 SUB drawBarChart(values AS double(50), nValues)
1740   REM TODO: add the respective type suffixes to your variable names if required 
1750   REM  
1760   REM  
1770   REM Used range of the Turtleizer screen 
1780   LET xSize = 500
1790   LET ySize = 500
1800   LET kMin = 0
1810   LET kMax = 0
1820   FOR k = 1 TO nValues-1
1830     IF values(k) > values(kMax) THEN
1840       LET kMax = k
1850     ELSE
1860       IF values(k) < values(kMin) THEN
1870         LET kMin = k
1880       END IF
1890     END IF
1900   NEXT k
1910   LET valMin = values(kMin)
1920   LET valMax = values(kMax)
1930   LET yScale = valMax * 1.0 / (ySize - 1)
1940   LET yAxis = ySize - 1
1950   IF valMin < 0 THEN
1960     IF valMax > 0 THEN
1970       LET yAxis = valMax * ySize * 1.0 / (valMax - valMin)
1980       LET yScale = (valMax - valMin) * 1.0 / (ySize - 1)
1990     ELSE
2000       LET yAxis = 1
2010       LET yScale = valMin * 1.0 / (ySize - 1)
2020     END IF
2030   END IF
2040   REM draw coordinate axes 
2050   gotoXY(1, ySize - 1)
2060   forward(ySize -1) : REM color = ffffff
2070   penUp()
2080   backward(yAxis) : REM color = ffffff
2090   right(90)
2100   penDown()
2110   forward(xSize -1) : REM color = ffffff
2120   penUp()
2130   backward(xSize-1) : REM color = ffffff
2140   LET stripeWidth = xSize / nValues
2150   FOR k = 0 TO nValues-1
2160     LET stripeHeight = values(k) * 1.0 / yScale
2170     SELECT CASE k % 3
2180       CASE 0
2190         setPenColor(255,0,0)
2200       CASE 1
2210         setPenColor(0, 255,0)
2220       CASE 2
2230         setPenColor(0, 0, 255)
2240     END SELECT
2250     fd(1) : REM color = ffffff
2260     left(90)
2270     penDown()
2280     fd(stripeHeight) : REM color = ffffff
2290     right(90)
2300     fd(stripeWidth - 1) : REM color = ffffff
2310     right(90)
2320     forward(stripeHeight) : REM color = ffffff
2330     left(90)
2340     penUp()
2350   NEXT k
2360 END SUB

REM = = = = 8< = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

