10 REM Concept and lisp implementation published by Joseph Weizenbaum (MIT): 
20 REM "ELIZA - A Computer Program For the Study of Natural Language Communication Between Man and Machine" - In: 
30 REM Computational Linguistis 1(1966)9, pp. 36-45 
40 REM Revision history: 
50 REM 2016-10-06 Initial version 
60 REM 2017-03-29 Two diagrams updated (comments translated to English) 
70 REM 2017-03-29 More keywords and replies added 
80 REM 2019-03-14 Replies and mapping reorganised for easier maintenance 
90 REM 2019-03-15 key map joined from keyword array and index map 
100 REM 2019-03-28 Keyword "bot" inserted (same reply ring as "computer") 
110 REM 2019-11-28 New global type "History" (to ensure a homogenous array) 
120 REM 2022-01-11 Measures against substition inversions a -> b -> a in conjugateStrings, reflexions revised. 
130 REM Generated by Structorizer 3.32-36 
140 
150 REM Copyright (C) 2018-05-14 Kay Gürtzig 
160 REM License: GPLv3-link 
170 REM GNU General Public License (V 3) 
180 REM https://www.gnu.org/licenses/gpl.html 
190 REM http://www.gnu.de/documents/gpl.de.html 
200 
210 REM  
220 REM program ELIZA
230 REM TODO: add the respective type suffixes to your variable names if required 
240 
250 REM histArray contains the most recent user replies as ring buffer; 
260 REM histIndex is the index where the next reply is to be stored (= index of the oldest 
270 REM cached user reply). 
280 REM Note: The depth of the history is to be specified by initializing a variable of this type, 
290 REM e.g. for a history of depth 5: 
300 REM myhistory <- History{{"", "", "", "", ""}, 0} 
310 type History = record{histArray: array of string; histIndex: int}
320 REM Associates a key word in the text with an index in the reply ring array 
330 type KeyMapEntry = record{ keyword: string; index: int }
340 
350 REM  
360 REM Title information 
370 PRINT "************* ELIZA **************"
380 PRINT "* Original design by J. Weizenbaum"
390 PRINT "**********************************"
400 PRINT "* Adapted for Basic on IBM PC by"
410 PRINT "* - Patricia Danielson"
420 PRINT "* - Paul Hashfield"
430 PRINT "**********************************"
440 PRINT "* Adapted for Structorizer by"
450 PRINT "* - Kay Gürtzig / FH Erfurt 2016"
460 PRINT "* Version: 2.4 (2022-01-11)"
470 PRINT "* (Requires at least Structorizer 3.30-03 to run)"
480 PRINT "**********************************"
490 REM Stores the last five inputs of the user in a ring buffer, 
500 REM the second component is the rolling (over-)write index. 
510 history <- History{{"", "", "", "", ""}, 0}
520 CONST replies <- setupReplies()
530 CONST reflexions <- setupReflexions()
540 CONST byePhrases <- setupGoodByePhrases()
550 CONST keyMap <- setupKeywords()
560 offsets[length(keyMap)-1] <- 0
570 isGone <- false
580 REM Starter 
590 PRINT "Hi! I\'m your new therapist. My name is Eliza. What\'s your problem?"
600 DO
610   INPUT userInput
620   REM Converts the input to lowercase, cuts out interpunctation 
630   REM and pads the string 
640   userInput <- normalizeInput(userInput)
650   isGone <- checkGoodBye(userInput, byePhrases)
660   IF not isGone THEN
670     reply <- "Please don\'t repeat yourself!"
680     isRepeated <- checkRepetition(history, userInput)
690     IF not isRepeated THEN
700       findInfo <- findKeyword(keyMap, userInput)
710       keyIndex <- findInfo[0]
720       IF keyIndex < 0 THEN
730         REM Should never happen... 
740         keyIndex <- length(keyMap)-1
750       END IF
760       var entry: KeyMapEntry <- keyMap[keyIndex]
770       REM Variable part of the reply 
780       varPart <- ""
790       IF length(entry.keyword) > 0 THEN
800         varPart <- conjugateStrings(userInput, entry.keyword, findInfo[1], reflexions)
810       END IF
820       replyRing <- replies[entry.index]
830       reply <- replyRing[offsets[keyIndex]]
840       offsets[keyIndex] <- (offsets[keyIndex] + 1) mod length(replyRing)
850       posAster <- pos("*", reply)
860       IF posAster > 0 THEN
870         IF varPart = " " THEN
880           reply <- "You will have to elaborate more for me to help you."
890         ELSE
900           delete(reply, posAster, 1)
910           insert(varPart, reply, posAster)
920         END IF
930       END IF
940       reply <- adjustSpelling(reply)
950     END IF
960     PRINT reply
970   END IF
980 LOOP UNTIL isGone
990 END
1000 REM  
1010 REM Cares for correct letter case among others 
1020 REM TODO: Add type-specific suffixes where necessary! 
1030 FUNCTION adjustSpelling(sentence AS String) AS String
1040   REM TODO: add the respective type suffixes to your variable names if required 
1050   REM  
1060   REM  
1070   result <- sentence
1080   position <- 1
1090   DO WHILE (position <= length(sentence)) and (copy(sentence, position, 1) = " ")
1100     position <- position + 1
1110   LOOP
1120   IF position <= length(sentence) THEN
1130     start <- copy(sentence, 1, position)
1140     delete(result, 1, position)
1150     insert(uppercase(start), result, 1)
1160   END IF
1170   FOR EACH word IN {" i ", " i\'"}
1180     position <- pos(word, result)
1190     DO WHILE position > 0
1200       delete(result, position+1, 1)
1210       insert("I", result, position+1)
1220       position <- pos(word, result)
1230     LOOP
1240   NEXT word
1250   RETURN result
1260 END FUNCTION
1270 REM  
1280 REM Checks whether the given text contains some kind of 
1290 REM good-bye phrase inducing the end of the conversation 
1300 REM and if so writes a correspding good-bye message and 
1310 REM returns true, otherwise false 
1320 REM TODO: Add type-specific suffixes where necessary! 
1330 FUNCTION checkGoodBye(text AS String, phrases AS String(50,0 TO 1)) AS boolean
1340   REM TODO: add the respective type suffixes to your variable names if required 
1350   REM  
1360   REM  
1370   FOR EACH pair IN phrases
1380     IF pos(pair[0], text) > 0 THEN
1390       PRINT pair[1]
1400       RETURN true
1410     END IF
1420   NEXT pair
1430   RETURN false
1440 END FUNCTION
1450 REM  
1460 REM TODO: Add type-specific suffixes where necessary! 
1470 FUNCTION conjugateStrings(sentence AS String, key AS String, keyPos AS integer, flexions AS String(50,0 TO 1)) AS String
1480   REM TODO: add the respective type suffixes to your variable names if required 
1490   REM  
1500   REM  
1510   result <- " " + copy(sentence, keyPos + length(key), length(sentence)) + " "
1520   FOR EACH pair IN flexions
1530     left <- ""
1540     right <- result
1550     pos0 <- pos(pair[0], right)
1560     pos1 <- pos(pair[1], right)
1570     DO WHILE pos0 > 0 or pos1 > 0
1580       REM Detect which of the two words of the pair matches first (lest a substitution should be reverted) 
1590       which <- 0
1600       position <- pos0
1610       IF (pos0 = 0) or ((pos1 > 0) and (pos1 < pos0)) THEN
1620         which <- 1
1630         position <- pos1
1640       END IF
1650       left <- left + copy(right, 1, position-1) + pair[1 - which]
1660       right <- copy(right, position + length(pair[which]), length(right))
1670       pos0 <- pos(pair[0], right)
1680       pos1 <- pos(pair[1], right)
1690     LOOP
1700     result <- left + right
1710   NEXT pair
1720   REM Eliminate multiple spaces (replaced by single ones) and vertical bars 
1730   FOR EACH str IN {"  ", "|"}
1740     position <- pos(str, result)
1750     DO WHILE position > 0
1760       result <- copy(result, 1, position-1) + copy(result, position+1, length(result))
1770       position <- pos(str, result)
1780     LOOP
1790   NEXT str
1800   RETURN result
1810 END FUNCTION
1820 REM  
1830 REM Converts the sentence to lowercase, eliminates all 
1840 REM interpunction (i.e. ',', '.', ';'), and pads the 
1850 REM sentence among blanks 
1860 REM TODO: Add type-specific suffixes where necessary! 
1870 FUNCTION normalizeInput(sentence AS String) AS String
1880   REM TODO: add the respective type suffixes to your variable names if required 
1890   REM  
1900   REM  
1910   sentence <- lowercase(sentence)
1920   FOR EACH symbol IN {'.', ',', ';', '!', '?'}
1930     position <- pos(symbol, sentence)
1940     DO WHILE position > 0
1950       sentence <- copy(sentence, 1, position-1) + copy(sentence, position+1, length(sentence))
1960       position <- pos(symbol, sentence)
1970     LOOP
1980   NEXT symbol
1990   result <- " " + sentence + " "
2000   RETURN result
2010 END FUNCTION
2020 REM  
2030 REM TODO: Add type-specific suffixes where necessary! 
2040 FUNCTION setupGoodByePhrases() AS String(50,0 TO 1)
2050   REM TODO: add the respective type suffixes to your variable names if required 
2060   REM  
2070   REM  
2080   phrases[0] <- {" shut", "Okay. If you feel that way I\'ll shut up. ... Your choice."}
2090   phrases[1] <- {"bye", "Well, let\'s end our talk for now. See you later. Bye."}
2100   RETURN phrases
2110 END FUNCTION
2120 REM  
2130 REM Returns an array of pairs of mutually substitutable words 
2140 REM The second word may contain a '|' in order to prevent an inverse 
2150 REM replacement. 
2160 REM TODO: Add type-specific suffixes where necessary! 
2170 FUNCTION setupReflexions() AS String(50,0 TO 1)
2180   REM TODO: add the respective type suffixes to your variable names if required 
2190   REM  
2200   REM  
2210   reflexions[0] <- {" are ", " am "}
2220   REM This is not always helpful (e.g. if it relates to things or third persons) 
2230   reflexions[1] <- {" were ", " was "}
2240   reflexions[2] <- {" you ", " i "}
2250   reflexions[3] <- {" yours ", " mine "}
2260   reflexions[4] <- {" yourself ", " myself "}
2270   reflexions[5] <- {" your ", " my "}
2280   reflexions[6] <- {" i\'ve ", " you\'ve "}
2290   reflexions[7] <- {" i\'m ", " you\'re "}
2300   REM We must not replace "you" by "me", not in particular after "I" had been replaced by "you". 
2310   reflexions[8] <- {" me ", " |you "}
2320   RETURN reflexions
2330 END FUNCTION
2340 REM  
2350 REM This routine sets up the reply rings addressed by the key words defined in 
2360 REM routine `setupKeywords()´ and mapped hitherto by the cross table defined 
2370 REM in `setupMapping()´ 
2380 REM TODO: Add type-specific suffixes where necessary! 
2390 FUNCTION setupReplies() AS String(50,50)
2400   REM TODO: add the respective type suffixes to your variable names if required 
2410   REM  
2420   REM  
2430   var replies: array of array of String
2440   REM We start with the highest index for performance reasons 
2450   REM (is to avoid frequent array resizing) 
2460   replies[29] <- { "Say, do you have any psychological problems?", "What does that suggest to you?", "I see.", "I'm not sure I understand you fully.", "Come come elucidate your thoughts.", "Can you elaborate on that?", "That is quite interesting."}
2470   replies[0] <- { "Don't you believe that I can*?", "Perhaps you would like to be like me?", "You want me to be able to*?"}
2480   replies[1] <- { "Perhaps you don't want to*?", "Do you want to be able to*?"}
2490   replies[2] <- { "What makes you think I am*?", "Does it please you to believe I am*?", "Perhaps you would like to be*?", "Do you sometimes wish you were*?"}
2500   replies[3] <- { "Don't you really*?", "Why don't you*?", "Do you wish to be able to*?", "Does that trouble you*?"}
2510   replies[4] <- { "Do you often feel*?", "Are you afraid of feeling*?", "Do you enjoy feeling*?"}
2520   replies[5] <- { "Do you really believe I don't*?", "Perhaps in good time I will*.", "Do you want me to*?"}
2530   replies[6] <- { "Do you think you should be able to*?", "Why can't you*?"}
2540   replies[7] <- { "Why are you interested in whether or not I am*?", "Would you prefer if I were not*?", "Perhaps in your fantasies I am*?"}
2550   replies[8] <- { "How do you know you can't*?", "Have you tried?","Perhaps you can now*."}
2560   replies[9] <- { "Did you come to me because you are*?", "How long have you been*?", "Do you believe it is normal to be*?", "Do you enjoy being*?"}
2570   replies[10] <- { "We were discussing you--not me.", "Oh, I*.", "You're not really talking about me, are you?"}
2580   replies[11] <- { "What would it mean to you if you got*?", "Why do you want*?", "Suppose you soon got*...", "What if you never got*?", "I sometimes also want*."}
2590   replies[12] <- { "Why do you ask?", "Does that question interest you?", "What answer would please you the most?", "What do you think?", "Are such questions on your mind often?", "What is it that you really want to know?", "Have you asked anyone else?", "Have you asked such questions before?", "What else comes to mind when you ask that?"}
2600   replies[13] <- { "Names don't interest me.", "I don't care about names -- please go on."}
2610   replies[14] <- { "Is that the real reason?", "Don't any other reasons come to mind?", "Does that reason explain anything else?", "What other reasons might there be?"}
2620   replies[15] <- { "Please don't apologize!", "Apologies are not necessary.", "What feelings do you have when you apologize?", "Don't be so defensive!"}
2630   replies[16] <- { "What does that dream suggest to you?", "Do you dream often?", "What persons appear in your dreams?", "Are you disturbed by your dreams?"}
2640   replies[17] <- { "How do you do ...please state your problem."}
2650   replies[18] <- { "You don't seem quite certain.", "Why the uncertain tone?", "Can't you be more positive?", "You aren't sure?", "Don't you know?"}
2660   replies[19] <- { "Are you saying no just to be negative?", "You are being a bit negative.", "Why not?", "Are you sure?", "Why no?"}
2670   replies[20] <- { "Why are you concerned about my*?", "What about your own*?"}
2680   replies[21] <- { "Can you think of a specific example?", "When?", "What are you thinking of?", "Really, always?"}
2690   replies[22] <- { "Do you really think so?", "But you are not sure you*?", "Do you doubt you*?"}
2700   replies[23] <- { "In what way?", "What resemblance do you see?", "What does the similarity suggest to you?", "What other connections do you see?", "Could there really be some connection?", "How?", "You seem quite positive."}
2710   replies[24] <- { "Are you sure?", "I see.", "I understand."}
2720   replies[25] <- { "Why do you bring up the topic of friends?", "Do your friends worry you?", "Do your friends pick on you?", "Are you sure you have any friends?", "Do you impose on your friends?", "Perhaps your love for friends worries you."}
2730   replies[26] <- { "Do computers worry you?", "Are you talking about me in particular?", "Are you frightened by machines?", "Why do you mention computers?", "What do you think machines have to do with your problem?", "Don't you think computers can help people?", "What is it about machines that worries you?"}
2740   replies[27] <- { "Do you sometimes feel uneasy without a smartphone?", "Have you had these phantasies before?", "Does the world seem more real for you via apps?"}
2750   replies[28] <- { "Tell me more about your family.", "Who else in your family*?", "What does family relations mean for you?", "Come on, How old are you?"}
2760   setupReplies <- replies
2770   RETURN setupReplies
2780 END FUNCTION
2790 REM  
2800 REM Checks whether newInput has occurred among the recently cached 
2810 REM input strings in the histArray component of history and updates the history. 
2820 REM TODO: Add type-specific suffixes where necessary! 
2830 FUNCTION checkRepetition(history AS History, newInput AS String) AS boolean
2840   REM TODO: add the respective type suffixes to your variable names if required 
2850   REM  
2860   REM  
2870   hasOccurred <- false
2880   IF length(newInput) > 4 THEN
2890     histDepth <- length(history.histArray)
2900     FOR i = 0 TO histDepth-1
2910       IF newInput = history.histArray[i] THEN
2920         hasOccurred <- true
2930       END IF
2940     NEXT i
2950     history.histArray[history.histIndex] <- newInput
2960     history.histIndex <- (history.histIndex + 1) mod (histDepth)
2970   END IF
2980   RETURN hasOccurred
2990 END FUNCTION
3000 REM  
3010 REM Looks for the occurrence of the first of the strings 
3020 REM contained in keywords within the given sentence (in 
3030 REM array order). 
3040 REM Returns an array of 
3050 REM 0: the index of the first identified keyword (if any, otherwise -1), 
3060 REM 1: the position inside sentence (0 if not found) 
3070 REM TODO: Add type-specific suffixes where necessary! 
3080 FUNCTION findKeyword(CONST keyMap AS KeyMapEntry(50), sentence AS String) AS integer(0 TO 1)
3090   REM TODO: add the respective type suffixes to your variable names if required 
3100   REM  
3110   REM  
3120   REM Contains the index of the keyword and its position in sentence 
3130   result <- {-1, 0}
3140   i <- 0
3150   DO WHILE (result[0] < 0) and (i < length(keyMap))
3160     var entry: KeyMapEntry <- keyMap[i]
3170     position <- pos(entry.keyword, sentence)
3180     IF position > 0 THEN
3190       result[0] <- i
3200       result[1] <- position
3210     END IF
3220     i <- i+1
3230   LOOP
3240   RETURN result
3250 END FUNCTION
3260 REM  
3270 REM The lower the index the higher the rank of the keyword (search is sequential). 
3280 REM The index of the first keyword found in a user sentence maps to a respective 
3290 REM reply ring as defined in `setupReplies()´. 
3300 REM TODO: Add type-specific suffixes where necessary! 
3310 FUNCTION setupKeywords() AS KeyMapEntry(50)
3320   REM TODO: add the respective type suffixes to your variable names if required 
3330   REM  
3340   REM  
3350   REM The empty key string (last entry) is the default clause - will always be found 
3360   keywords[39] <- KeyMapEntry{"", 29}
3370   keywords[0] <- KeyMapEntry{"can you ", 0}
3380   keywords[1] <- KeyMapEntry{"can i ", 1}
3390   keywords[2] <- KeyMapEntry{"you are ", 2}
3400   keywords[3] <- KeyMapEntry{"you\'re ", 2}
3410   keywords[4] <- KeyMapEntry{"i don't ", 3}
3420   keywords[5] <- KeyMapEntry{"i feel ", 4}
3430   keywords[6] <- KeyMapEntry{"why don\'t you ", 5}
3440   keywords[7] <- KeyMapEntry{"why can\'t i ", 6}
3450   keywords[8] <- KeyMapEntry{"are you ", 7}
3460   keywords[9] <- KeyMapEntry{"i can\'t ", 8}
3470   keywords[10] <- KeyMapEntry{"i am ", 9}
3480   keywords[11] <- KeyMapEntry{"i\'m ", 9}
3490   keywords[12] <- KeyMapEntry{"you ", 10}
3500   keywords[13] <- KeyMapEntry{"i want ", 11}
3510   keywords[14] <- KeyMapEntry{"what ", 12}
3520   keywords[15] <- KeyMapEntry{"how ", 12}
3530   keywords[16] <- KeyMapEntry{"who ", 12}
3540   keywords[17] <- KeyMapEntry{"where ", 12}
3550   keywords[18] <- KeyMapEntry{"when ", 12}
3560   keywords[19] <- KeyMapEntry{"why ", 12}
3570   keywords[20] <- KeyMapEntry{"name ", 13}
3580   keywords[21] <- KeyMapEntry{"cause ", 14}
3590   keywords[22] <- KeyMapEntry{"sorry ", 15}
3600   keywords[23] <- KeyMapEntry{"dream ", 16}
3610   keywords[24] <- KeyMapEntry{"hello ", 17}
3620   keywords[25] <- KeyMapEntry{"hi ", 17}
3630   keywords[26] <- KeyMapEntry{"maybe ", 18}
3640   keywords[27] <- KeyMapEntry{" no", 19}
3650   keywords[28] <- KeyMapEntry{"your ", 20}
3660   keywords[29] <- KeyMapEntry{"always ", 21}
3670   keywords[30] <- KeyMapEntry{"think ", 22}
3680   keywords[31] <- KeyMapEntry{"alike ", 23}
3690   keywords[32] <- KeyMapEntry{"yes ", 24}
3700   keywords[33] <- KeyMapEntry{"friend ", 25}
3710   keywords[34] <- KeyMapEntry{"computer", 26}
3720   keywords[35] <- KeyMapEntry{"bot ", 26}
3730   keywords[36] <- KeyMapEntry{"smartphone", 27}
3740   keywords[37] <- KeyMapEntry{"father ", 28}
3750   keywords[38] <- KeyMapEntry{"mother ", 28}
3760   RETURN keywords
3770 END FUNCTION

REM = = = = 8< = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

