10 REM Concept and lisp implementation published by Joseph Weizenbaum (MIT): 
20 REM "ELIZA - A Computer Program For the Study of Natural Language Communication Between Man and Machine" - In: 
30 REM Computational Linguistis 1(1966)9, pp. 36-45 
40 REM Revision history: 
50 REM 2016-10-06 Initial version 
60 REM 2017-03-29 Two diagrams updated (comments translated to English) 
70 REM 2017-03-29 More keywords and replies added 
80 REM 2019-03-14 Replies and mapping reorganised for easier maintenance 
90 REM 2019-03-15 key map joined from keyword array and index map 
100 REM 2019-03-28 Keyword "bot" inserted (same reply ring as "computer") 
110 REM Generated by Structorizer 3.32-36 
120 
130 REM Copyright (C) 2018-05-14 ??? 
140 REM License: GPLv3-link 
150 REM GNU General Public License (V 3) 
160 REM https://www.gnu.org/licenses/gpl.html 
170 REM http://www.gnu.de/documents/gpl.de.html 
180 
190 REM  
200 REM program ELIZA
210 REM TODO: add the respective type suffixes to your variable names if required 
220 
230 type KeyMapEntry = record{ keyword: string; index: int }
240 
250 REM  
260 REM Title information 
270 PRINT "************* ELIZA **************"
280 PRINT "* Original design by J. Weizenbaum"
290 PRINT "**********************************"
300 PRINT "* Adapted for Basic on IBM PC by"
310 PRINT "* - Patricia Danielson"
320 PRINT "* - Paul Hashfield"
330 PRINT "**********************************"
340 PRINT "* Adapted for Structorizer by"
350 PRINT "* - Kay Gürtzig / FH Erfurt 2016"
360 PRINT "* Version: 2.2 (2019-03-28)"
370 PRINT "**********************************"
380 REM Stores the last five inputs of the user in a ring buffer, 
390 REM the first element is the current insertion index 
400 history <- {0, "", "", "", "", ""}
410 CONST replies <- setupReplies()
420 CONST reflexions <- setupReflexions()
430 CONST byePhrases <- setupGoodByePhrases()
440 CONST keyMap <- setupKeywords()
450 offsets[length(keyMap)-1] <- 0
460 isGone <- false
470 REM Starter 
480 PRINT "Hi! I\'m your new therapist. My name is Eliza. What\'s your problem?"
490 DO
500   INPUT userInput
510   REM Converts the input to lowercase, cuts out interpunctation 
520   REM and pads the string 
530   userInput <- normalizeInput(userInput)
540   isGone <- checkGoodBye(userInput, byePhrases)
550   IF not isGone THEN
560     reply <- "Please don\'t repeat yourself!"
570     isRepeated <- checkRepetition(history, userInput)
580     IF not isRepeated THEN
590       findInfo <- findKeyword(keyMap, userInput)
600       keyIndex <- findInfo[0]
610       IF keyIndex < 0 THEN
620         REM Should never happen... 
630         keyIndex <- length(keyMap)-1
640       END IF
650       var entry: KeyMapEntry <- keyMap[keyIndex]
660       REM Variable part of the reply 
670       varPart <- ""
680       IF length(entry.keyword) > 0 THEN
690         varPart <- conjugateStrings(userInput, entry.keyword, findInfo[1], reflexions)
700       END IF
710       replyRing <- replies[entry.index]
720       reply <- replyRing[offsets[keyIndex]]
730       offsets[keyIndex] <- (offsets[keyIndex] + 1) mod length(replyRing)
740       posAster <- pos("*", reply)
750       IF posAster > 0 THEN
760         IF varPart = " " THEN
770           reply <- "You will have to elaborate more for me to help you."
780         ELSE
790           delete(reply, posAster, 1)
800           insert(varPart, reply, posAster)
810         END IF
820       END IF
830       reply <- adjustSpelling(reply)
840     END IF
850     PRINT reply
860   END IF
870 LOOP UNTIL isGone
880 END
890 REM  
900 REM Cares for correct letter case among others 
910 REM TODO: Add type-specific suffixes where necessary! 
920 FUNCTION adjustSpelling(sentence AS String) AS String
930   REM TODO: add the respective type suffixes to your variable names if required 
940   REM  
950   REM  
960   result <- sentence
970   position <- 1
980   DO WHILE (position <= length(sentence)) and (copy(sentence, position, 1) = " ")
990     position <- position + 1
1000   LOOP
1010   IF position <= length(sentence) THEN
1020     start <- copy(sentence, 1, position)
1030     delete(result, 1, position)
1040     insert(uppercase(start), result, 1)
1050   END IF
1060   FOR EACH word IN {" i ", " i\'"}
1070     position <- pos(word, result)
1080     DO WHILE position > 0
1090       delete(result, position+1, 1)
1100       insert("I", result, position+1)
1110       position <- pos(word, result)
1120     LOOP
1130   NEXT word
1140   RETURN result
1150 END FUNCTION
1160 REM  
1170 REM Checks whether the given text contains some kind of 
1180 REM good-bye phrase inducing the end of the conversation 
1190 REM and if so writes a correspding good-bye message and 
1200 REM returns true, otherwise false 
1210 REM TODO: Add type-specific suffixes where necessary! 
1220 FUNCTION checkGoodBye(text AS String, phrases AS String(50,0 TO 1)) AS boolean
1230   REM TODO: add the respective type suffixes to your variable names if required 
1240   REM  
1250   REM  
1260   FOR EACH pair IN phrases
1270     IF pos(pair[0], text) > 0 THEN
1280       saidBye <- true
1290       PRINT pair[1]
1300       RETURN true
1310     END IF
1320   NEXT pair
1330   RETURN false
1340 END FUNCTION
1350 REM  
1360 REM Checks whether newInput has occurred among the last 
1370 REM length(history) - 1 input strings and updates the history 
1380 REM TODO: Add type-specific suffixes where necessary! 
1390 FUNCTION checkRepetition(history AS array, newInput AS String) AS boolean
1400   REM TODO: add the respective type suffixes to your variable names if required 
1410   REM  
1420   REM  
1430   hasOccurred <- false
1440   IF length(newInput) > 4 THEN
1450     currentIndex <- history[0];
1460     FOR i = 1 TO length(history)-1
1470       IF newInput = history[i] THEN
1480         hasOccurred <- true
1490       END IF
1500     NEXT i
1510     history[history[0]+1] <- newInput
1520     history[0] <- (history[0] + 1) mod (length(history) - 1)
1530   END IF
1540   RETURN hasOccurred
1550 END FUNCTION
1560 REM  
1570 REM TODO: Add type-specific suffixes where necessary! 
1580 FUNCTION conjugateStrings(sentence AS String, key AS String, keyPos AS integer, flexions AS String(50,0 TO 1)) AS String
1590   REM TODO: add the respective type suffixes to your variable names if required 
1600   REM  
1610   REM  
1620   result <- " " + copy(sentence, keyPos + length(key), length(sentence)) + " "
1630   FOR EACH pair IN flexions
1640     left <- ""
1650     right <- result
1660     position <- pos(pair[0], right)
1670     DO WHILE position > 0
1680       left <- left + copy(right, 1, position-1) + pair[1]
1690       right <- copy(right, position + length(pair[0]), length(right))
1700       position <- pos(pair[0], right)
1710     LOOP
1720     result <- left + right
1730   NEXT pair
1740   REM Eliminate multiple spaces 
1750   position <- pos("  ", result)
1760   DO WHILE position > 0
1770     result <- copy(result, 1, position-1) + copy(result, position+1, length(result))
1780     position <- pos("  ", result)
1790   LOOP
1800   RETURN result
1810 END FUNCTION
1820 REM  
1830 REM Converts the sentence to lowercase, eliminates all 
1840 REM interpunction (i.e. ',', '.', ';'), and pads the 
1850 REM sentence among blanks 
1860 REM TODO: Add type-specific suffixes where necessary! 
1870 FUNCTION normalizeInput(sentence AS String) AS String
1880   REM TODO: add the respective type suffixes to your variable names if required 
1890   REM  
1900   REM  
1910   sentence <- lowercase(sentence)
1920   FOR EACH symbol IN {'.', ',', ';', '!', '?'}
1930     position <- pos(symbol, sentence)
1940     DO WHILE position > 0
1950       sentence <- copy(sentence, 1, position-1) + copy(sentence, position+1, length(sentence))
1960       position <- pos(symbol, sentence)
1970     LOOP
1980   NEXT symbol
1990   result <- " " + sentence + " "
2000   RETURN result
2010 END FUNCTION
2020 REM  
2030 REM TODO: Add type-specific suffixes where necessary! 
2040 FUNCTION setupGoodByePhrases() AS String(50,0 TO 1)
2050   REM TODO: add the respective type suffixes to your variable names if required 
2060   REM  
2070   REM  
2080   phrases[0] <- {" shut", "Okay. If you feel that way I\'ll shut up. ... Your choice."}
2090   phrases[1] <- {"bye", "Well, let\'s end our talk for now. See you later. Bye."}
2100   RETURN phrases
2110 END FUNCTION
2120 REM  
2130 REM Returns an array of pairs of mutualy substitutable  
2140 REM TODO: Add type-specific suffixes where necessary! 
2150 FUNCTION setupReflexions() AS String(50,0 TO 1)
2160   REM TODO: add the respective type suffixes to your variable names if required 
2170   REM  
2180   REM  
2190   reflexions[0] <- {" are ", " am "}
2200   reflexions[1] <- {" were ", " was "}
2210   reflexions[2] <- {" you ", " I "}
2220   reflexions[3] <- {" your", " my"}
2230   reflexions[4] <- {" i\'ve ", " you\'ve "}
2240   reflexions[5] <- {" i\'m ", " you\'re "}
2250   reflexions[6] <- {" me ", " you "}
2260   reflexions[7] <- {" my ", " your "}
2270   reflexions[8] <- {" i ", " you "}
2280   reflexions[9] <- {" am ", " are "}
2290   RETURN reflexions
2300 END FUNCTION
2310 REM  
2320 REM This routine sets up the reply rings addressed by the key words defined in 
2330 REM routine `setupKeywords()´ and mapped hitherto by the cross table defined 
2340 REM in `setupMapping()´ 
2350 REM TODO: Add type-specific suffixes where necessary! 
2360 FUNCTION setupReplies() AS String(50,50)
2370   REM TODO: add the respective type suffixes to your variable names if required 
2380   REM  
2390   REM  
2400   var replies: array of array of String
2410   REM We start with the highest index for performance reasons 
2420   REM (is to avoid frequent array resizing) 
2430   replies[29] <- { "Say, do you have any psychological problems?", "What does that suggest to you?", "I see.", "I'm not sure I understand you fully.", "Come come elucidate your thoughts.", "Can you elaborate on that?", "That is quite interesting."}
2440   replies[0] <- { "Don't you believe that I can*?", "Perhaps you would like to be like me?", "You want me to be able to*?"}
2450   replies[1] <- { "Perhaps you don't want to*?", "Do you want to be able to*?"}
2460   replies[2] <- { "What makes you think I am*?", "Does it please you to believe I am*?", "Perhaps you would like to be*?", "Do you sometimes wish you were*?"}
2470   replies[3] <- { "Don't you really*?", "Why don't you*?", "Do you wish to be able to*?", "Does that trouble you*?"}
2480   replies[4] <- { "Do you often feel*?", "Are you afraid of feeling*?", "Do you enjoy feeling*?"}
2490   replies[5] <- { "Do you really believe I don't*?", "Perhaps in good time I will*.", "Do you want me to*?"}
2500   replies[6] <- { "Do you think you should be able to*?", "Why can't you*?"}
2510   replies[7] <- { "Why are you interested in whether or not I am*?", "Would you prefer if I were not*?", "Perhaps in your fantasies I am*?"}
2520   replies[8] <- { "How do you know you can't*?", "Have you tried?","Perhaps you can now*."}
2530   replies[9] <- { "Did you come to me because you are*?", "How long have you been*?", "Do you believe it is normal to be*?", "Do you enjoy being*?"}
2540   replies[10] <- { "We were discussing you--not me.", "Oh, I*.", "You're not really talking about me, are you?"}
2550   replies[11] <- { "What would it mean to you if you got*?", "Why do you want*?", "Suppose you soon got*...", "What if you never got*?", "I sometimes also want*."}
2560   replies[12] <- { "Why do you ask?", "Does that question interest you?", "What answer would please you the most?", "What do you think?", "Are such questions on your mind often?", "What is it that you really want to know?", "Have you asked anyone else?", "Have you asked such questions before?", "What else comes to mind when you ask that?"}
2570   replies[13] <- { "Names don't interest me.", "I don't care about names -- please go on."}
2580   replies[14] <- { "Is that the real reason?", "Don't any other reasons come to mind?", "Does that reason explain anything else?", "What other reasons might there be?"}
2590   replies[15] <- { "Please don't apologize!", "Apologies are not necessary.", "What feelings do you have when you apologize?", "Don't be so defensive!"}
2600   replies[16] <- { "What does that dream suggest to you?", "Do you dream often?", "What persons appear in your dreams?", "Are you disturbed by your dreams?"}
2610   replies[17] <- { "How do you do ...please state your problem."}
2620   replies[18] <- { "You don't seem quite certain.", "Why the uncertain tone?", "Can't you be more positive?", "You aren't sure?", "Don't you know?"}
2630   replies[19] <- { "Are you saying no just to be negative?", "You are being a bit negative.", "Why not?", "Are you sure?", "Why no?"}
2640   replies[20] <- { "Why are you concerned about my*?", "What about your own*?"}
2650   replies[21] <- { "Can you think of a specific example?", "When?", "What are you thinking of?", "Really, always?"}
2660   replies[22] <- { "Do you really think so?", "But you are not sure you*?", "Do you doubt you*?"}
2670   replies[23] <- { "In what way?", "What resemblance do you see?", "What does the similarity suggest to you?", "What other connections do you see?", "Could there really be some connection?", "How?", "You seem quite positive."}
2680   replies[24] <- { "Are you sure?", "I see.", "I understand."}
2690   replies[25] <- { "Why do you bring up the topic of friends?", "Do your friends worry you?", "Do your friends pick on you?", "Are you sure you have any friends?", "Do you impose on your friends?", "Perhaps your love for friends worries you."}
2700   replies[26] <- { "Do computers worry you?", "Are you talking about me in particular?", "Are you frightened by machines?", "Why do you mention computers?", "What do you think machines have to do with your problem?", "Don't you think computers can help people?", "What is it about machines that worries you?"}
2710   replies[27] <- { "Do you sometimes feel uneasy without a smartphone?", "Have you had these phantasies before?", "Does the world seem more real for you via apps?"}
2720   replies[28] <- { "Tell me more about your family.", "Who else in your family*?", "What does family relations mean for you?", "Come on, How old are you?"}
2730   setupReplies <- replies
2740   RETURN setupReplies
2750 END FUNCTION
2760 REM  
2770 REM Looks for the occurrence of the first of the strings 
2780 REM contained in keywords within the given sentence (in 
2790 REM array order). 
2800 REM Returns an array of 
2810 REM 0: the index of the first identified keyword (if any, otherwise -1), 
2820 REM 1: the position inside sentence (0 if not found) 
2830 REM TODO: Add type-specific suffixes where necessary! 
2840 FUNCTION findKeyword(CONST keyMap AS KeyMapEntry(50), sentence AS String) AS integer(0 TO 1)
2850   REM TODO: add the respective type suffixes to your variable names if required 
2860   REM  
2870   REM  
2880   REM Contains the index of the keyword and its position in sentence 
2890   result <- {-1, 0}
2900   i <- 0
2910   DO WHILE (result[0] < 0) and (i < length(keyMap))
2920     var entry: KeyMapEntry <- keyMap[i]
2930     position <- pos(entry.keyword, sentence)
2940     IF position > 0 THEN
2950       result[0] <- i
2960       result[1] <- position
2970     END IF
2980     i <- i+1
2990   LOOP
3000   RETURN result
3010 END FUNCTION
3020 REM  
3030 REM The lower the index the higher the rank of the keyword (search is sequential). 
3040 REM The index of the first keyword found in a user sentence maps to a respective 
3050 REM reply ring as defined in `setupReplies()´. 
3060 REM TODO: Add type-specific suffixes where necessary! 
3070 FUNCTION setupKeywords() AS KeyMapEntry(50)
3080   REM TODO: add the respective type suffixes to your variable names if required 
3090   REM  
3100   REM  
3110   REM The empty key string (last entry) is the default clause - will always be found 
3120   keywords[39] <- KeyMapEntry{"", 29}
3130   keywords[0] <- KeyMapEntry{"can you ", 0}
3140   keywords[1] <- KeyMapEntry{"can i ", 1}
3150   keywords[2] <- KeyMapEntry{"you are ", 2}
3160   keywords[3] <- KeyMapEntry{"you\'re ", 2}
3170   keywords[4] <- KeyMapEntry{"i don't ", 3}
3180   keywords[5] <- KeyMapEntry{"i feel ", 4}
3190   keywords[6] <- KeyMapEntry{"why don\'t you ", 5}
3200   keywords[7] <- KeyMapEntry{"why can\'t i ", 6}
3210   keywords[8] <- KeyMapEntry{"are you ", 7}
3220   keywords[9] <- KeyMapEntry{"i can\'t ", 8}
3230   keywords[10] <- KeyMapEntry{"i am ", 9}
3240   keywords[11] <- KeyMapEntry{"i\'m ", 9}
3250   keywords[12] <- KeyMapEntry{"you ", 10}
3260   keywords[13] <- KeyMapEntry{"i want ", 11}
3270   keywords[14] <- KeyMapEntry{"what ", 12}
3280   keywords[15] <- KeyMapEntry{"how ", 12}
3290   keywords[16] <- KeyMapEntry{"who ", 12}
3300   keywords[17] <- KeyMapEntry{"where ", 12}
3310   keywords[18] <- KeyMapEntry{"when ", 12}
3320   keywords[19] <- KeyMapEntry{"why ", 12}
3330   keywords[20] <- KeyMapEntry{"name ", 13}
3340   keywords[21] <- KeyMapEntry{"cause ", 14}
3350   keywords[22] <- KeyMapEntry{"sorry ", 15}
3360   keywords[23] <- KeyMapEntry{"dream ", 16}
3370   keywords[24] <- KeyMapEntry{"hello ", 17}
3380   keywords[25] <- KeyMapEntry{"hi ", 17}
3390   keywords[26] <- KeyMapEntry{"maybe ", 18}
3400   keywords[27] <- KeyMapEntry{" no", 19}
3410   keywords[28] <- KeyMapEntry{"your ", 20}
3420   keywords[29] <- KeyMapEntry{"always ", 21}
3430   keywords[30] <- KeyMapEntry{"think ", 22}
3440   keywords[31] <- KeyMapEntry{"alike ", 23}
3450   keywords[32] <- KeyMapEntry{"yes ", 24}
3460   keywords[33] <- KeyMapEntry{"friend ", 25}
3470   keywords[34] <- KeyMapEntry{"computer", 26}
3480   keywords[35] <- KeyMapEntry{"bot ", 26}
3490   keywords[36] <- KeyMapEntry{"smartphone", 27}
3500   keywords[37] <- KeyMapEntry{"father ", 28}
3510   keywords[38] <- KeyMapEntry{"mother ", 28}
3520   RETURN keywords
3530 END FUNCTION

REM = = = = 8< = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

