Rem Test for indirect and concurrent includes 
Rem Generated by Structorizer 3.32-31 
Rem  
Rem program TestMain
Rem TODO: Check and accomplish your variable declarations here: 

Dim a1 As Integer
a2 <- "doof"
Dim b1 As String
b2 <- 3.9

Dim c2 As Integer
Dim c1 As ???
Dim b2 As double
Dim a2 As String
Rem  
a1 <- 7
b1 <- a2 + " oder blöd"
c1 <- a1 * b2
c2 <- testSub(c1, a1 + b2, b1)
PRINT a1; " "; a2; " "; b1; " "; b2
End
Rem  
Rem TODO: Check (and specify if needed) the argument and result types! 
Function testSub(c1 As real, param2 As real, b1 As String) As Integer
  Rem TODO: Check and accomplish your variable declarations here: 
  Rem  
  Dim d2 As String
  Dim d1 As Integer
  Dim a2 As String
  Rem  
  d1 <- a1
  d2 <- a2
  a1 <- 15
  Return length(a2 + b1) + floor(c1) * ceil(param2)
End Function

Rem = = = = 8< = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

