#!/bin/bash

# Test for indirect and concurrent includes 
# (generated by Structorizer 3.32-33) 

# Copyright (C) 2020-04-13 Kay Gürtzig 
# License: GPLv3-link 
# GNU General Public License (V 3) 
# https://www.gnu.org/licenses/gpl.html 
# http://www.gnu.de/documents/gpl.de.html 

function testSub() {
    local c1=$1
    local param2=$2
    local b1=$3

    # TODO: Check and revise the syntax of all expressions! 

    d1 <- a1
    d2 <- a2
    a1 <- 15
    return  length(a2 + b1) + floor(c1) * ceil(param2)
}
# = = = = 8< = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

# TODO: Check and revise the syntax of all expressions! 

a1 <- 7
b1 <- a2 + " oder blöd"
c1 <- a1 * b2
c2 <- testSub(c1, a1 + b2, b1)
echo a1, " ", a2, " ", b1, " ", b2
