/*
    Structorizer
    A little tool which you can use to create Nassi-Schneiderman Diagrams (NSD)

    Copyright (C) 2009  Bob Fisch

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any
    later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package lu.fisch.structorizer.executor;

/******************************************************************************************************
 *
 *      Author:         Bob Fisch
 *
 *      Description:    This class represents the Output text area for executor console mode.
 *
 ******************************************************************************************************
 *
 *      Revision List
 *
 *      Author          Date            Description
 *      ------			----			-----------
 *      Kay Gürtzig     2016.04.08      First Issue (implementing enhancement request #137)
 *      Kay Gürtzig     2016.04.12      Functionality accomplished
 *      Kay Gürtzig     2016-04-25      Scrolling to last line ensured
 *
 ******************************************************************************************************
 *
 *      Comment:  /
 *         
 ******************************************************************************************************///

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Rectangle;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import lu.fisch.structorizer.gui.IconLoader;

@SuppressWarnings("serial")
public class OutputConsole extends JFrame {

	private JPanel panel;
	private JTextArea textArea;
	
	public OutputConsole()
	{
		initComponents();
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    private void initComponents() {

    	panel = new JPanel();
    	
    	setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Structorizer Output Console");
    	this.setIconImage(IconLoader.ico004.getImage());
    	
    	textArea = new JTextArea();
    	textArea.setBackground(Color.BLACK);
    	textArea.setForeground(Color.WHITE);
    	JScrollPane scrText = new JScrollPane(textArea);
    	panel.setLayout(new BorderLayout());
    	panel.add(scrText, BorderLayout.CENTER);
    	textArea.setLineWrap(true);
    	this.add(panel, null);
    	//textArea.setRows(25);
    	//textArea.setColumns(80);
    	this.setSize(500, 250);
    }
    
    public void clear()
    {
    	this.textArea.setText("");
    }
    
    /**
     * Appends string _text to the textArea as is, i.e. without additional newline.
     * @param _text - a string
     */
    public void write(String _text)
    {
    	this.textArea.append(_text);
    	// Scroll to end (if there is an easier way, I just didn't find it).
    	Rectangle rect = this.textArea.getBounds();
    	rect.y = rect.height - 1;
    	rect.height = 1;
    	this.textArea.scrollRectToVisible(rect);
    }

    /**
     * Appends string _text in the specified (foreground) colour to the textArea
     * as is, i.e. without additional newline.
     * TODO Remark: Color attribute doesn't work in the current version
     * @param _text - a string
     * @param _colour - the text colour to use
     */
    public void write(String _text, Color _colour)
    {
    	// TODO: In order to be able to format something we must use a Document
    	//Color oldColour = this.textArea.getForeground();
    	//this.textArea.setForeground(_colour);
    	this.textArea.append(_text);
    	//this.textArea.setForeground(oldColour);
    	// Scroll to end (if there is an easier way, I just didn't find it).
    	Rectangle rect = this.textArea.getBounds();
    	rect.y = rect.height - 1;
    	rect.height = 1;
    	this.textArea.scrollRectToVisible(rect);
    }

    /**
     * Appends string _text to the textArea with additional newline.
     * @param _text - a string
     */
    public void writeln(String _text)
    {
    	this.write(_text + "\n");
    }

    /**
     * Appends string _text in the specified (foreground) colour to the textArea
     * with additional newline.
     * TODO Remark: Color attribute doesn't work in the current version
     * @param _text - a string
     * @param _colour - the text colour to use
     */
    public void writeln(String _text, Color _colour)
    {
    	this.write(_text + "\n", _colour);
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputConsole().setVisible(true);
            }
        });
    }
	
	
}
